services:
  api:
    build:
      context: .
      args:
        - FLUTTER_BASE_URL=${HTML_ROOT:-/}
    restart: always
    ports:
      - ${HOST_PORT:-80}:${API_PORT:-3456}
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-password}@sos-db:5432/${POSTGRES_USER:-user}
      - API_PORT=${API_PORT:-3456}
      - HTML_ROOT=${HTML_ROOT:-}
    depends_on:
      db-prod:
        condition: service_healthy
    profiles:
      - prod

  db-prod:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - ./api/postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
    hostname: sos-db
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user}"]
      interval: 5s
      timeout: 10s
      retries: 5
    profiles:
      - prod

  db-dev:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - ./api/postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
    hostname: sos-db
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user}"]
      interval: 5s
      timeout: 10s
      retries: 5
    profiles:
      - dev

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    profiles:
      - dev